repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black

  - repo: https://github.com/pycqa/pylint
    rev: main
    hooks:
    - id: pylint
      language: system
      args:
        - --fail-under=9
