language: python
python: 3.7
install:
  - pip install -r reqs.txt
  - pip install -U pytest
  - pip install .
  - pip install codecov
script:
  - python -m pytest -vv --cov-report term-missing --cov=logical_backup tests
after_success:
  - codecov
